version: '3.7'

services:
  db:
    image: postgres:17
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_USER=app
      - POSTGRES_DB=expense_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d expense_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8079:8079'
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SECRET_KEY=SECRET_KEY
      - DATABASE_URL=postgresql+psycopg://app:secretpassword@db:5432/expense_db
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - REACT_APP_SENTRY_DSN=<REACT_APP_SENTRY_DSN>
      - REACT_APP_API_BASE_URL=http://backend:8079/api

volumes:
  db_data:
